---
title: "3 Post-Imputation"
date: "`r Sys.Date()`"
output:
  rmdformats::robobook:
    self_contained: true
    thumbnails: false
    lightbox: true
    gallery: false
    highlight: tango
params:
  project: test-gwas-test
  chip: test-chip
  reference_panel: test-panel
  qualities:  ../tests/output/03_imputation_quality/test-gwas.qualities.txt
---

```{r setup, include=FALSE}
library(ggplot2)
library(DT)
knitr::opts_chunk$set(echo = FALSE)
```

```{r warning=FALSE}
qualities <- read.csv(params$qualities, sep = ',')
```

# Summary

| Parameter        | Value                                      |
| ---------------- |--------------------------------------------|
| Project          | `r params$project`                         |
| Chip             | `r params$chip`                            |
| Reference Panel  | `r params$reference_panel`                 |
| Imputed SNPs     | `r sum(qualities$count_Rsq)`               |


# Imputation Quality by MAF


```{r warning=FALSE}
ggplot(qualities) + geom_line(aes(x=MAF, y=mean_Rsq, fill=1)) + facet_wrap(~source) + ylim(c(0,1)) + ggtitle(paste(params$project, ' (', params$chip, ')'))
```
