---
title: "5 Pairwise IBD estimation"
date: "`r Sys.Date()`"
output:
  rmdformats::robobook:
    self_contained: true
    thumbnails: false
    lightbox: true
    gallery: false
    highlight: tango
params:
  genome_filename: /Users/lukfor/Askimed Dropbox/Lukas Forer/Genepi/Projekte/covid-gwas/20211206/new-paca/plink.genome
  famname: /Users/lukfor/Askimed Dropbox/Lukas Forer/Genepi/Projekte/covid-gwas/20211206/new-paca/covid-gwas.fam
---

```{r setup, include=FALSE}
library(ggplot2)
library(DT)
library(dplyr)
knitr::opts_chunk$set(echo = FALSE)
```

# Pairwise IBD estimation (plink)

 using estimates of pairwise IBD to find pairs of individuals who look too similar to eachother, i.e. more than we would expect by chance in a random sample.

```{r warning=FALSE}
genome=read.table(params$genome_filename, header = TRUE, stringsAsFactors = FALSE)

hist(genome$PI_HAT)

datatable(genome %>% filter(PI_HAT > 0.1875))




print("reading genome file")
data = read.table(params$genome_filename, h=T)

hist(data$PI_HAT, col="RED", breaks=100, xlab="Estimated mean pairwise IBD", main="")


plot(data$PI_HAT, xlab="Index", ylab="Proportion IBD")
abline(h=0.185,col="RED",lty=2)


out = which(data$PI_HAT > 0.185)
#write.table(data[out,], file=paste(outputpathname, "/fail-IBD-check.txt", sep=""), col.names=T, row.names=F)

print("calculate avgDST")
dst = data
ind <- read.table(params$famname, header=F, stringsAsFactors=F)
ind$AvgDST <- NA
for (i in 1:nrow(ind)) {
    ind$AvgDST[i] <- mean(dst[dst$IID1==ind$V2[i] | dst$IID2==ind$V2[i], c("DST")])
}
ind<-ind[, c("V1","V2","AvgDST")]

#pdf(paste(outputpathname, "/DST-plot.pdf", sep=""))
plot(density(dst$DST), main="All DST", xlab="DST")
rug(dst$DST)

plot(density(ind$AvgDST), main="Average DST", xlab="AvgDST")
rug(ind$AvgDST)
abline(v=0.678, col="blue")
abline(v=0.66, col="blue")
#dev.off()

dst = data.frame(
	FID=ind$V1,
	IID=ind$V2,
	AVGDST=ind$AvgDST
)
datatable(dst)
#write.table(dst, paste(outputpathname, "ind-dst.txt", sep="/"), col.names=T, row.names=F,quote=F)

```
