---
title: "Pre-Imputation-QC"
output: html_document
params:
  project: test-gwas-test
  chip: test-chip
  samples: ../tests/output/single/29sep20_GSA_PLINK.qc.samples ../tests/output/single/31aug20_GSA_PLINK.qc.samples
  snps: ../tests/output/single/29sep20_GSA_PLINK.qc.snps ../tests/output/single/31aug20_GSA_PLINK.qc.snps
  samples_merged: ../tests/output/test-gwas.qc.samples
  samples_excluded: ../tests/output/test-gwas.qc.samples.excluded
  filter_statistics: ../tests/output/single/29sep20_GSA_PLINK.statistics ../tests/output/single/31aug20_GSA_PLINK.statistics
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(warn = -1)

library(ggplot2)
library(DT)
library(dplyr)
htmltools::tagList(datatable(cars))

```


```{r, echo=FALSE}
samples <- read.csv(params$samples_merged, sep="")
samples_count <- length(unique(samples$sample))
if (!file.size(params$samples_excluded) == 0) {
    excluded_samples <- read.csv(params$samples_excluded, sep="",header = FALSE)
    excluded_samples_count <- dim(excluded_samples)[1]
}else {
  excluded_samples_count = 0
}
```

## Summary

| Parameter     | Value                                              |
| ------------- |----------------------------------------------------|
| Project       | `r params$project`                                 |
| Chip          | `r params$chip`                                    |
| Samples       | `r samples_count - excluded_samples_count` samples |
| SNPs          | TODO                                               |

## Excluded Samples

<div class="alert alert-info">
**`r excluded_samples_count`** samples excluded due to low call rate.
</div>

```{r, echo=FALSE}
if (excluded_samples_count > 0) {
    datatable(excluded_samples)
}
```

## All Samples

```{r, echo=FALSE}
ggplot(samples, aes(x=call_rate)) + geom_histogram(binwidth = 0.05)
```

## Runs

TODO:

- number of runs
- SNPs per run
- avg Sample call rate

### SNPs after each step

```{r filters, results='asis'}
filenames <- unlist(strsplit(params$filter_statistics, " "))
for (filename in filenames){
  statistics <- read.csv(filename, sep="")
  print(htmltools::tagList((datatable(statistics))))
}
```

### Sample Call Rate

```{r samples, echo=FALSE}
filenames <- unlist(strsplit(params$samples, " "))
for (filename in filenames){
  samples <- read.csv(filename, sep="")
  print(
    ggplot(samples, aes(x=chunk, y=sample)) +
      geom_tile(aes(fill=call_rate)) +
      scale_fill_gradient(low = "red", high = "white",limits=c(0,1)) +
      ggtitle(filename)
    )
}
```

### SNP Call Rate

```{r snps, echo=FALSE}
filenames <- unlist(strsplit(params$snps, " "))
for (filename in filenames){
  snps <- read.csv(filename, sep="")
  print(
    ggplot(snps, aes(x=call_rate)) +
      geom_histogram(binwidth = 0.05) +
      ggtitle(filename)
    )
}
```
